export const LOCATION_CHANGE = '@@router/LOCATION_CHANGE';
// Suggestions Fetch
export const SUGGESTIONS_REQUEST = 'SUGGESTIONS_REQUEST';
export const SUGGESTIONS_SUCCESS = 'SUGGESTIONS_SUCCESS';
export const SUGGESTIONS_FAILURE = 'SUGGESTIONS_FAILURE';
// Layers Fetch
export const LAYERS_REQUEST = 'LAYERS_REQUEST';
export const LAYERS_SUCCESS = 'LAYERS_SUCCESS';
export const LAYERS_FAILURE = 'LAYERS_FAILURE';
// Layer Vector Fetch
export const LAYER_VECTOR_REQUEST = 'LAYER_VECTOR_REQUEST';
export const LAYER_VECTOR_SUCCESS = 'LAYER_VECTOR_SUCCESS';
export const LAYER_VECTOR_FAILURE = 'LAYER_VECTOR_FAILURE';
// Location Fetch
export const LOCATION_REQUEST = 'LOCATION_REQUEST';
export const LOCATION_SUCCESS = 'LOCATION_SUCCESS';
export const LOCATION_FAILURE = 'LOCATION_FAILURE';

export const SET_SELECTED_FEATURE = 'SET_SELECTED_FEATURE';
export const SET_MAP_ZOOM = 'SET_MAP_ZOOM';
export const SET_MAP_LAYER = 'SET_MAP_LAYER';
export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';
export const SET_SELECTED_LAYER = 'SET_SELECTED_LAYER';
export const SET_LOCATION_TYPE = 'SET_LOCATION_TYPE';
export const SET_MAP_CENTER = 'SET_MAP_CENTER';
